name: IAM
on:
  workflow_dispatch:
  push:

jobs:
  terraform:
    uses: jithin/gh-workflow-terraform/workflow.yaml@master
    secrets: inherit
    with:
      account-type: workload
      boundary: TestEngineering
      DeployRole: testEngineering/TestEngineeringInfrastrcutureDeployRole
      working-directory: infrastructure
